/**
 * Job: agent:generate-briefing
 *
 * When triggered from the web app, this job:
 * 1. Fetches the project and change request context
 * 2. Builds the developer briefing (same logic as generateDeveloperBriefing action)
 * 3. Saves the AgentRun record in the DB
 * 4. Future: push to GitHub Issues, call an AI API, etc.
 */
import { prisma } from "@/lib/db";
import { AgentRunStatus } from "@prisma/client";
import type { AgentBriefingJobData } from "@/lib/queue";

export async function processAgentBriefing(data: AgentBriefingJobData) {
  const { projectId, changeRequestId, actorUserId } = data;

  const project = await prisma.projectWorkspace.findUnique({
    where: { id: projectId },
    include: {
      client: { select: { companyName: true } },
      repositories: true,
    },
  });

  if (!project) {
    throw new Error(`Project not found: ${projectId}`);
  }

  let changeRequest = null;
  if (changeRequestId) {
    changeRequest = await prisma.changeRequest.findUnique({
      where: { id: changeRequestId },
      select: {
        title: true,
        description: true,
        impact: true,
        sourceType: true,
      },
    });
  }

  const primaryRepo = project.repositories[0];

  const briefing = buildBriefing(project, changeRequest, primaryRepo ?? null);

  // Save the run record
  const agentRun = await prisma.agentRun.create({
    data: {
      projectId,
      changeRequestId: changeRequestId ?? null,
      initiatedByUserId: actorUserId,
      provider: "internal-worker",
      status: AgentRunStatus.COMPLETED,
      promptSnapshot: briefing,
      outputSummary: "Briefing generated by background worker",
    },
  });

  // Future hooks:
  // - await pushToGitHubIssue(briefing, primaryRepo)
  // - await callAiApi(briefing)
  // - await sendSlackNotification(...)

  console.log(`[agent-briefing] Briefing saved as AgentRun ${agentRun.id} for project ${projectId}`);
  return { agentRunId: agentRun.id };
}

function buildBriefing(
  project: {
    name: string;
    status: string;
    techStack: string | null;
    domainName: string | null;
    hostingInfo: string | null;
    client: { companyName: string };
    repositories: Array<{ repoUrl: string; defaultBranch: string; issueBoardUrl: string | null }>;
  },
  changeRequest: {
    title: string;
    description: string;
    impact: string;
    sourceType: string;
  } | null,
  primaryRepo: { repoUrl: string; defaultBranch: string; issueBoardUrl: string | null } | null
): string {
  return `# Developer Briefing

## Project Context
- **Project**: ${project.name}
- **Client**: ${project.client.companyName}
- **Status**: ${project.status}
- **Tech Stack**: ${project.techStack ?? "Not specified"}
- **Domain**: ${project.domainName ?? "Not specified"}
- **Hosting**: ${project.hostingInfo ?? "Not specified"}
- **Repository**: ${primaryRepo?.repoUrl ?? "No repository linked"}
- **Default Branch**: ${primaryRepo?.defaultBranch ?? "Not specified"}

${changeRequest
  ? `## Change Request
- **Title**: ${changeRequest.title}
- **Impact**: ${changeRequest.impact}
- **Source**: ${changeRequest.sourceType}

## Requested Change
${changeRequest.description}`
  : "## Requested Change\n_No specific change request linked. Refer to project scope and description._"
}

## Acceptance Criteria
${changeRequest
  ? changeRequest.description
      .split(/[.!?]/)
      .map((s) => s.trim())
      .filter((s) => s.length > 10)
      .slice(0, 5)
      .map((line) => `- [ ] ${line}`)
      .join("\n") || "- [ ] Feature implemented as described"
  : "- [ ] Feature implemented as described\n- [ ] No regressions introduced"
}

## Repository Context
- Repo: ${primaryRepo?.repoUrl ?? "N/A"}
- Branch: ${primaryRepo?.defaultBranch ?? "N/A"}
- Issues: ${primaryRepo?.issueBoardUrl ?? "N/A"}

## Review Checklist
- [ ] Code reviewed
- [ ] Tested on mobile
- [ ] Cross-browser tested
- [ ] Client approved
`;
}
